### ISSUE TITLE
scripts/3rdparty/VRHealthAPIConnect.gd is missing from repository

### ISSUE THREAD

**Issue by ChristophHaag** [mgschwan/VRWorkout#4]

**Comment by mgschwan** [comment]
Thanks for the info.
VRHealthAPIConnect.gd is not yet available in the public repository because the VRHealth Institute is currently rewriting the server backend and it can't be used for now (only for testing)

Once that is finished this script will be added back in but I fixed it for now by loading the script conditionally

Fixed in 42bb96abb1d5142c6da2a41f2ac44c1dd867fbaf
